name: Create APP and publish

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Bump version
      uses: chkfung/android-version-actions@v1.2.1
      with:
        gradlePath: app/build.gradle # or app/build.gradle.kts 
        versionCode: ${{github.run_number}}
        versionName: ${{ env.RELEASE_VERSION }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew bundleRelease
    - name: upload artefact to App Center
      uses: wzieba/AppCenter-Github-Action@v1
      with:
        appName: karlosarr/app
        token: ${{secrets.APP_CENTER_TOKEN}}
        group: Collaborators,Public
        file: app/build/outputs/bundle/release/app-release.aab
        notifyTesters: true
        debug: false
    - uses: actions/upload-artifact@v3
      with:
        name: APP
        path: app/build/outputs/bundle/release/app-release.aab
